export default {
  attribute: "attributes",
  category: "categories",
  classes: "classes",
  collection: "collections",
  configure: "configures",
  comment: "comments",
  commentProject: "projects",
  commentSubject: "subjects",
  company: "companies",
  grade: "grades",
  great: "greats",
  initial: "initials",
  jurisdiction: "jurisdictions",
  product: "products",
  right: "rights",
  role: "roles",
  school: "schools",
  student: "students",
  tutorial: "tutorials",
  user: "users",
  client: "clients",
}
